export function Plant() {

}

export const plantList = [
   {
      "name":"Alyssum",
      "id":0,
      "tileColor":"#1fbce8"
   },
   {
      "name":"Amaranthus",
      "id":1,
      "tileColor":"#213308"
   },
   {
      "name":"Amaryllis",
      "id":2,
      "tileColor":"#8822da"
   },
   {
      "name":"Ammi Majus",
      "id":3,
      "tileColor":"#dc41ab"
   },
   {
      "name":"Angelonia",
      "id":4,
      "tileColor":"#00a2a2"
   },
   {
      "name":"Asclepias",
      "id":5,
      "tileColor":"#6f61d3"
   },
   {
      "name":"Aster",
      "id":6,
      "tileColor":"#556fc7"
   },
   {
      "name":"Baby's Breath",
      "id":7,
      "tileColor":"#717794"
   },
   {
      "name":"Balsam",
      "id":8,
      "tileColor":"#4fe4e5"
   },
   {
      "name":"Begonia",
      "id":9,
      "tileColor":"#aa8330"
   },
   {
      "name":"Bells of Ireland",
      "id":10,
      "tileColor":"#55f44e"
   },
   {
      "name":"Blue Eyed Daisies",
      "id":11,
      "tileColor":"#ad1c9e"
   },
   {
      "name":"Caladium",
      "id":12,
      "tileColor":"#4b6472"
   },
   {
      "name":"Calendula",
      "id":13,
      "tileColor":"#20b03b"
   },
   {
      "name":"Calibrachoa",
      "id":14,
      "tileColor":"#89eafe"
   },
   {
      "name":"Calla",
      "id":15,
      "tileColor":"#11e791"
   },
   {
      "name":"Canna",
      "id":16,
      "tileColor":"#e6d273"
   },
   {
      "name":"Celosia",
      "id":17,
      "tileColor":"#1d5108"
   },
   {
      "name":"Chrysanthemum",
      "id":18,
      "tileColor":"#3137a3"
   },
   {
      "name":"Cleome",
      "id":19,
      "tileColor":"#8e5fc6"
   },
   {
      "name":"Coleus",
      "id":20,
      "tileColor":"#8f2acf"
   },
   {
      "name":"Cornflower",
      "id":21,
      "tileColor":"#e47f28"
   },
   {
      "name":"Cosmos",
      "id":22,
      "tileColor":"#392ac6"
   },
   {
      "name":"Cuphea",
      "id":23,
      "tileColor":"#33f99c"
   },
   {
      "name":"Cypress Vine",
      "id":24,
      "tileColor":"#7c4e66"
   },
   {
      "name":"Dahlias",
      "id":25,
      "tileColor":"#1aa559"
   },
   {
      "name":"Dianthus",
      "id":26,
      "tileColor":"#87fe61"
   },
   {
      "name":"Dichondra",
      "id":27,
      "tileColor":"#00fd23"
   },
   {
      "name":"Dusty Miller",
      "id":28,
      "tileColor":"#c1e546"
   },
   {
      "name":"Elephant Ears",
      "id":29,
      "tileColor":"#24309b"
   },
   {
      "name":"Flowers for Cutting",
      "id":30,
      "tileColor":"#18b49a"
   },
   {
      "name":"Four O'Clocks",
      "id":31,
      "tileColor":"#35569e"
   },
   {
      "name":"Gaillardia",
      "id":32,
      "tileColor":"#ce3eee"
   },
   {
      "name":"Geraniums",
      "id":33,
      "tileColor":"#0b478d"
   },
   {
      "name":"Gerbera",
      "id":34,
      "tileColor":"#238b15"
   },
   {
      "name":"Gladiolus",
      "id":35,
      "tileColor":"#7a85a0"
   },
   {
      "name":"Gomphrena",
      "id":36,
      "tileColor":"#5b2bfc"
   },
   {
      "name":"Ice Plants",
      "id":37,
      "tileColor":"#8c2ce7"
   },
   {
      "name":"Impatiens",
      "id":38,
      "tileColor":"#c31b95"
   },
   {
      "name":"Ipomopsis",
      "id":39,
      "tileColor":"#cc81a4"
   },
   {
      "name":"Laurentia",
      "id":40,
      "tileColor":"#9ff80e"
   },
   {
      "name":"Lisianthus",
      "id":41,
      "tileColor":"#4b1248"
   },
   {
      "name":"Lobelias",
      "id":42,
      "tileColor":"#ac3456"
   },
   {
      "name":"Marigolds",
      "id":43,
      "tileColor":"#40a9de"
   },
   {
      "name":"Millet",
      "id":44,
      "tileColor":"#1ba77b"
   },
   {
      "name":"Moonflowers",
      "id":45,
      "tileColor":"#4d29ca"
   },
   {
      "name":"Morning Glories",
      "id":46,
      "tileColor":"#a0642a"
   },
   {
      "name":"Nasturtium",
      "id":47,
      "tileColor":"#fcb0c5"
   },
   {
      "name":"Nemophila",
      "id":48,
      "tileColor":"#5365b6"
   },
   {
      "name":"Nicotiana",
      "id":49,
      "tileColor":"#f2274f"
   },
   {
      "name":"Ornamental Kale",
      "id":50,
      "tileColor":"#d6fb15"
   },
   {
      "name":"Pansies",
      "id":51,
      "tileColor":"#fd6d18"
   },
   {
      "name":"Pennisetum",
      "id":52,
      "tileColor":"#1e5271"
   },
   {
      "name":"Pentas",
      "id":53,
      "tileColor":"#c3a2af"
   },
   {
      "name":"Petunias",
      "id":54,
      "tileColor":"#98adbf"
   },
   {
      "name":"Phlox Flowers",
      "id":55,
      "tileColor":"#45ccd6"
   },
   {
      "name":"Poppy",
      "id":56,
      "tileColor":"#156d35"
   },
   {
      "name":"Portulaca",
      "id":57,
      "tileColor":"#fd655f"
   },
   {
      "name":"Rudbeckias",
      "id":58,
      "tileColor":"#3bb20b"
   },
   {
      "name":"Salvia",
      "id":59,
      "tileColor":"#e13087"
   },
   {
      "name":"Scabiosa",
      "id":60,
      "tileColor":"#5a8711"
   },
   {
      "name":"Scaevola",
      "id":61,
      "tileColor":"#54365b"
   },
   {
      "name":"Snapdragons",
      "id":62,
      "tileColor":"#965f44"
   },
   {
      "name":"Statice",
      "id":63,
      "tileColor":"#a895a4"
   },
   {
      "name":"Strawflowers",
      "id":64,
      "tileColor":"#09811e"
   },
   {
      "name":"Sunflowers",
      "id":65,
      "tileColor":"#285f81"
   },
   {
      "name":"Sweet Peas",
      "id":66,
      "tileColor":"#50ee94"
   },
   {
      "name":"Thunbergia",
      "id":67,
      "tileColor":"#efe126"
   },
   {
      "name":"Tithonia",
      "id":68,
      "tileColor":"#803e89"
   },
   {
      "name":"Torenia",
      "id":69,
      "tileColor":"#325bef"
   },
   {
      "name":"Tuberose",
      "id":70,
      "tileColor":"#c4d929"
   },
   {
      "name":"Verbenas",
      "id":71,
      "tileColor":"#37073c"
   },
   {
      "name":"Vincas",
      "id":72,
      "tileColor":"#3f1ad5"
   },
   {
      "name":"Violas",
      "id":73,
      "tileColor":"#e2f8bd"
   },
   {
      "name":"Zinnias",
      "id":74,
      "tileColor":"#1cc232"
   }
]
